Repository jongwooo/fake-news, pull requests merged in 2022-12, with the labels that each got.

#1 feat: Implement text mining
  data/FakeNews.csv
  fake-news.R
Labels: enhancement

#2 chore: Create workflow
  .Rprofile
  .github/workflows/r.yml
  renv.lock
  renv/.gitignore
  renv/activate.R
  renv/settings.dcf
Labels: chore

#3 chore: Set R version to v4.1.3
  .github/workflows/r.yml
Labels: chore

#5 perf: Remove rows with missing values
  fake-news.R
Labels: performance

#6 perf: Remove empty documents at tdm
  fake-news.R
Labels: performance

#8 perf: Remove non-specific data
  fake-news.R
Labels: performance

#9 refactor: Use %in% operator
  fake-news.R
Labels: refactoring

#10 style: Update fake-news.R to format code
  fake-news.R
Labels: style
